version: "3.9"

services:
  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
    ports:
      - "5431:5432"
    restart: unless-stopped
    volumes:
      - ./provision/postgres/01-databases.sql:/docker-entrypoint-initdb.d/01-databases.sql
    networks:
      - lingo-network

  # web:
  #   image: lingo
  #   container_name: lingo-web
  #   build:
  #     dockerfile: Dockerfile
  #     target: debug
  #   command: ["--", "web"]
  #   environment:
  #     LINGO_DB_URL: postgres://postgres:postgres@db:5432/relay?sslmode=disable
  #     LINGO_PORT: 8080
  #     LINGO_AES_256_KEY: ${LINGO_AES_256_KEY:-}
  #   volumes:
  #     - ./certs:/src/lingo/certs
  #   ports:
  #     - "8090:8080"
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  #     - relay-migration
  #   networks:
  #     - lingo-network

  relay-migration:
    image: arigaio/atlas:0.17.0
    container_name: lingo-relay-migrate
    command: migrate apply --url "postgres://postgres:postgres@db:5432/relay?sslmode=disable"
    volumes:
      - ./migrations:/migrations
    networks:
      - lingo-network
    depends_on:
      - db

  relay:
    image: lingo
    container_name: lingo-relay
    build:
      dockerfile: Dockerfile
      target: debug
    command: ["--", "serve", "relay"]
    environment:
      LINGO_DB_URL: postgres://postgres:postgres@db:5432/relay?sslmode=disable
      LINGO_PORT: 8080
      LINGO_TLS_CERT_FILE: /src/lingo/certs/lingo.crt
      LINGO_TLS_KEY_FILE: /src/lingo/certs/lingo.key
      LINGO_SIGNING_KEY_REGISTRATION: ${LINGO_SIGNING_KEY_REGISTRATION:-}
      LINGO_SIGNING_KEY_AUTHENTICATION: ${LINGO_SIGNING_KEY_AUTHENTICATION:-}
    volumes:
      - ./certs:/src/lingo/certs
    ports:
      - "8091:8080"
      - "9090:9090"
      - "2345:2345"
    restart: unless-stopped
    depends_on:
      - db
      - relay-migration
    networks:
      - lingo-network

networks:
  lingo-network:
    driver: bridge
