version: "3.9"

services:
  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
    ports:
      - "5431:5432"
    restart: unless-stopped
    volumes:
      - ./provision/postgres/01-databases.sql:/docker-entrypoint-initdb.d/01-databases.sql
    networks:
      - lingo-network

  relay-migration:
    image: arigaio/atlas:0.15.0
    container_name: lingo-relay-migrate
    command: migrate apply --url "postgres://postgres:postgres@db:5432/relay?sslmode=disable"
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db

  relay:
    image: lingo
    container_name: lingo-relay
    build:
      dockerfile: Dockerfile
      target: debug
    command: ["--", "relay"]
    environment:
      LINGO_DB_URL: postgres://postgres:postgres@db:5432/relay?sslmode=disable
    ports:
      - "8080:8080"
      - "2345:2345"
    restart: unless-stopped
    depends_on:
      - db
      - relay-migration
    networks:
      - lingo-network

networks:
  lingo-network:
    driver: bridge
